package com.example.aikeyboard.text.composing

class TelesComposer : Composer {
    override val id = "telex"
    override val label = "Telex"
    override val toRead = 2  // Number of characters to read ahead for composition

    // Danh sách từ điển để giữ nguyên từ tiếng Anh khi gõ Telex
    private val rules = mapOf( 
        "w" to "w",
        "ww" to "w",
        "algorithm" to "algorithm",
        "api" to "api",
        "application" to "application",
        "architecture" to "architecture",
        "array" to "array",
        "async" to "async",
        "attribute" to "attribute",
        "authentication" to "authentication",
        "binary" to "binary",
        "bug" to "bug",
        "cache" to "cache",
        "class" to "class",
        "code" to "code",
        "commit" to "commit",
        "compile" to "compile",
        "component" to "component",
        "computer" to "computer",
        "config" to "config",
        "constant" to "constant",
        "container" to "container",
        "data" to "data",
        "database" to "database",
        "debug" to "debug",
        "dependency" to "dependency",
        "deploy" to "deploy",
        "design" to "design",
        "development" to "development",
        "device" to "device",
        "document" to "document",
        "domain" to "domain",
        "error" to "error",
        "event" to "event",
        "exception" to "exception",
        "file" to "file",
        "filter" to "filter",
        "format" to "format",
        "framework" to "framework",
        "function" to "function",
        "git" to "git",
        "github" to "github",
        "gradle" to "gradle",
        "hardware" to "hardware",
        "hash" to "hash",
        "http" to "http",
        "implementation" to "implementation",
        "import" to "import",
        "index" to "index",
        "input" to "input",
        "instance" to "instance",
        "interface" to "interface",
        "java" to "java",
        "javascript" to "javascript",
        "json" to "json",
        "keyboard" to "keyboard",
        "kotlin" to "kotlin",
        "language" to "language",
        "library" to "library",
        "linux" to "linux",
        "list" to "list",
        "log" to "log",
        "logic" to "logic",
        "loop" to "loop",
        "memory" to "memory",
        "message" to "message",
        "method" to "method",
        "mobile" to "mobile",
        "model" to "model",
        "module" to "module",
        "network" to "network",
        "node" to "node",
        "object" to "object",
        "package" to "package",
        "parameter" to "parameter",
        "pattern" to "pattern",
        "platform" to "platform",
        "plugin" to "plugin",
        "process" to "process",
        "program" to "program",
        "project" to "project",
        "protocol" to "protocol",
        "query" to "query",
        "queue" to "queue",
        "react" to "react",
        "reference" to "reference",
        "regex" to "regex",
        "release" to "release",
        "repository" to "repository",
        "request" to "request",
        "resource" to "resource",
        "response" to "response",
        "rest" to "rest",
        "return" to "return",
        "route" to "route",
        "runtime" to "runtime",
        "schema" to "schema",
        "script" to "script",
        "security" to "security",
        "server" to "server",
        "service" to "service",
        "session" to "session",
        "setting" to "setting",
        "shell" to "shell",
        "software" to "software",
        "source" to "source",
        "spring" to "spring",
        "sql" to "sql",
        "stack" to "stack",
        "standard" to "standard",
        "state" to "state",
        "static" to "static",
        "storage" to "storage",
        "stream" to "stream",
        "string" to "string",
        "structure" to "structure",
        "style" to "style",
        "system" to "system",
        "table" to "table",
        "task" to "task",
        "template" to "template",
        "terminal" to "terminal",
        "test" to "test",
        "thread" to "thread",
        "time" to "time",
        "token" to "token",
        "tool" to "tool",
        "type" to "type",
        "update" to "update",
        "user" to "user",
        "value" to "value",
        "variable" to "variable",
        "version" to "version",
        "view" to "view",
        "virtual" to "virtual",
        "web" to "web",
        "windows" to "windows",
        "xml" to "xml",
    )

    override fun getActions(precedingText: String, toInsert: String): Pair<Int, String> {
        // Check if we have a rule that matches the combination of precedingText and toInsert
        val input = precedingText + toInsert
        for ((pattern, replacement) in rules) {
            if (input.endsWith(pattern)) {
                // Return the number of characters to delete from precedingText and the replacement
                return Pair(pattern.length - toInsert.length, replacement)
            }
        }
        // No rule matches, just append the character
        return Pair(0, toInsert)
    }
}
